// Xai type declarations define plugin contracts.
export const buildAssistantMessage: (...args: unknown[]) => unknown;
export const buildOllamaChatRequest: (...args: unknown[]) => unknown;
export const convertToOllamaMessages: (...args: unknown[]) => unknown;
export const createConfiguredOllamaCompatStreamWrapper: (...args: unknown[]) => unknown;
export const createConfiguredOllamaStreamFn: (...args: unknown[]) => unknown;
export const createOllamaStreamFn: (...args: unknown[]) => unknown;
export const createOllamaEmbeddingProvider: (...args: unknown[]) => unknown;
export const isOllamaCompatProvider: (...args: unknown[]) => unknown;
export const resolveOllamaBaseUrlForRun: (...args: unknown[]) => unknown;
export const resolveOllamaCompatNumCtxEnabled: (...args: unknown[]) => unknown;
export const shouldInjectOllamaCompatNumCtx: (...args: unknown[]) => unknown;
export const parseNdjsonStream: (...args: unknown[]) => unknown;
export const wrapOllamaCompatNumCtx: (...args: unknown[]) => unknown;
