export const MAX_WORKER_BUNDLE_ARCHIVE_BYTES = 512 * 1024 * 1024;
const MAX_WORKER_BUNDLE_EXPANDED_BYTES = 2 * 1024 * 1024 * 1024;
const MAX_WORKER_BUNDLE_ENTRIES = 250_000;

export const DEFAULT_WORKER_BUNDLE_ARCHIVE_LIMITS = {
  maxEntries: MAX_WORKER_BUNDLE_ENTRIES,
  maxExpandedBytes: MAX_WORKER_BUNDLE_EXPANDED_BYTES,
} as const;
